parameters:
#    tmp_jr_beer_consumer.example.class: TmpJr\BeerConsumerBundle\Example

services:
#    tmp_jr_beer_consumer.example:
#        class: %tmp_jr_beer_consumer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
